
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BookList, BookViewSet

# Create a router instance
router = DefaultRouter()

# Register the BookViewSet with the router
# The 'r' prefix denotes a raw string.
router.register(r'books_all', BookViewSet, basename='book_all')

# The API URLs are now determined by the router.

urlpatterns = [
    path('books/', BookList.as_view(), name='book-list'),
    # Include the URLs generated by the router
    path('', include(router.urls)),
]

